enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config


[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "19.16.39"
included-patches = "'Force hide player buttons background'"
excluded-patches = "'Alternative thumbnails' 'Bypass image region restrictions' 'Change player flyout menu toggles' 'Custom Shorts action buttons' 'Custom branding icon for YouTube' 'Enable debug logging' 'Enable gradient loading screen' 'Hook download actions' 'Layout switch' 'Remove viewer discretion dialog' 'Theme' 'Translations for YouTube'"
patches-source = "inotia00/revanced-patches" # where to fetch patches bundle from. default: "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations" # where to fetch integrations from. default: "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
patches-version = "v4.10.3"
#integrations-version = "v1.11.4-dev.1"
#cli-version = "v4.6.1"

[Music]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "YT-Advanced ReVanced"
arch = "arm64-v8a"
version = "6.33.52"
included-patches = "'Enable color match player' 'Hide voice search button'"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music' 'Enable custom filter' 'Hide playlist card' 'Remember shuffle state' 'Return YouTube Dislike' 'Translations'"
