enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations" 
cli-source = "revanced/revanced-cli"
patches-version = "v4.4.0" 
integrations-version = "v1.5.0"
cli-version = "v4.5.0"
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Announcements' 'Enable debugging' 'External downloads' 'Swipe controls' 'Wide searchbar' 'Hide captions button' 'Hide autoplay button' 'Theme' 'Change start page' 'Hide seekbar' 'Comments' 'Hide timestamp'"
version = "auto"

