enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "YT-Advanced ReVanced"
included-patches = "'Hide voice search button'"
excluded-patches = "'Alternative thumbnails' 'Change start page' 'Custom branding heading' 'Custom branding icon YouTube' 'Custom branding name YouTube' 'Enable external browser' 'Enable gradient loading screen' 'Enable language switch' 'Enable new splash animation' 'Enable song search' 'Enable wide search bar' 'Hide seekbar' 'Hide time stamp' 'Hide trending searches' 'Theme' 'Translations'"

[Music]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
rv-brand = "YT-Advanced ReVanced"
arch = "arm64-v8a"
version = "6.33.52"
included-patches = "'Enable color match player' 'Hide voice search button'"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music' 'Enable custom filter' 'Hide playlist card' 'Remember shuffle state' 'Return YouTube Dislike' 'Translations'"
